# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build travana-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t travana-api`.
FROM docker.io/node:lts-alpine

WORKDIR /app

RUN addgroup --system travana-api && \
          adduser --system -G travana-api travana-api

COPY dist/apps/travana-api travana-api/
RUN chown -R travana-api:travana-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix travana-api --omit=dev -f install

CMD [ "node", "travana-api" ]
